# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [17]:
import numpy as np
A = np.array([[2, 3,3], [1, 4,3], [7, 6,3]])
B = B = np.array([[5, 3,3], [2, 2,3], [1,2,3]])
C = np.array([[4,3,4], [3,6,7], [9,3,2]])

print(A.dot(B+C))
print(A.dot(B) + (A.dot(C)))

[[ 63  51  59]
 [ 59  53  62]
 [123 105 124]]
[[ 63  51  59]
 [ 59  53  62]
 [123 105 124]]


## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [18]:
# Your code here 
print(A.dot(B.dot(C)))
print((A.dot(B)).dot(C))

[[346 237 250]
 [331 222 231]
 [749 528 569]]
[[346 237 250]
 [331 222 231]
 [749 528 569]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [20]:
B.dot(A) == A.dot(B)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [24]:
A.transpose().dot(B) == B.transpose().dot(A)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = A^T \cdot B^T $

In [5]:
# Your code here 

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 